// <auto-generated />
using System;
using HiggsfieldTutorial.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HiggsfieldTutorial.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405151151_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.GenerationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("HiggsfieldRequestId")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultUrl")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HiggsfieldRequestId");

                    b.ToTable("GenerationJobs");
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.PromptExample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultImageUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Upvotes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PromptExamples");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Category = "Landscape",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = true,
                            MediaType = "image",
                            ModelId = "higgsfield-ai/soul/standard",
                            Prompt = "A breathtaking mountain landscape at golden hour, dramatic clouds, mist in the valleys, shot with an IMAX camera, ultra-wide angle, cinematic color grading",
                            Tags = "[\"landscape\",\"cinematic\",\"golden-hour\"]",
                            Title = "Cinematic Landscape",
                            Upvotes = 42
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Category = "Fashion",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = true,
                            MediaType = "image",
                            ModelId = "higgsfield-ai/soul/v2",
                            Prompt = "Professional fashion photography of a woman in an elegant red dress, studio lighting with soft shadows, Vogue magazine style, shot on Hasselblad, editorial look",
                            Tags = "[\"fashion\",\"portrait\",\"studio\"]",
                            Title = "Fashion Portrait",
                            Upvotes = 38
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Category = "Product",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = true,
                            MediaType = "image",
                            ModelId = "higgsfield-ai/nano-banana/pro",
                            Prompt = "Minimalist product shot of a luxury perfume bottle on a white marble surface, soft directional lighting, water droplets, commercial photography style, clean background",
                            Tags = "[\"product\",\"commercial\",\"minimalist\"]",
                            Title = "Product Photography",
                            Upvotes = 35
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Category = "Motion",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = true,
                            MediaType = "video",
                            ModelId = "higgsfield-ai/dop/standard",
                            Prompt = "A person walking in slow motion through a neon-lit Tokyo alley at night, rain reflections on the ground, cinematic camera following from behind",
                            Tags = "[\"video\",\"cinematic\",\"neon\",\"slow-motion\"]",
                            Title = "Slow Motion Walk",
                            Upvotes = 56
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            Category = "Motion",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsFeatured = false,
                            MediaType = "video",
                            ModelId = "kling-video/v3/image-to-video",
                            Prompt = "Smooth 360-degree camera orbit around the subject standing in a sunlit meadow, gentle wind moving hair and grass, shallow depth of field",
                            Tags = "[\"video\",\"orbit\",\"camera-movement\"]",
                            Title = "Camera Orbit",
                            Upvotes = 28
                        });
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.Tutorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tutorials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Category = "GettingStarted",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Beginner",
                            EstimatedMinutes = 10,
                            IsPublished = true,
                            Slug = "getting-started",
                            SortOrder = 1,
                            Summary = "Learn the basics of Higgsfield AI platform",
                            Tags = "[\"intro\",\"basics\"]",
                            Title = "Getting Started with Higgsfield"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Category = "ImageGeneration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Beginner",
                            EstimatedMinutes = 15,
                            IsPublished = true,
                            Slug = "image-generation-basics",
                            SortOrder = 2,
                            Summary = "Create stunning images using text prompts",
                            Tags = "[\"images\",\"text-to-image\"]",
                            Title = "Image Generation Basics"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Category = "VideoGeneration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Beginner",
                            EstimatedMinutes = 20,
                            IsPublished = true,
                            Slug = "video-generation-images",
                            SortOrder = 3,
                            Summary = "Transform static images into dynamic videos",
                            Tags = "[\"video\",\"image-to-video\"]",
                            Title = "Video Generation from Images"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Category = "PromptEngineering",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 25,
                            IsPublished = true,
                            Slug = "prompt-engineering",
                            SortOrder = 4,
                            Summary = "Master the art of writing effective prompts",
                            Tags = "[\"prompts\",\"advanced\"]",
                            Title = "Prompt Engineering for AI Art"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Category = "CharacterCreation",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 15,
                            IsPublished = true,
                            Slug = "soul-id-character",
                            SortOrder = 5,
                            Summary = "Create unique AI characters with Soul ID",
                            Tags = "[\"character\",\"soul-id\"]",
                            Title = "Soul ID Character Creation"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            Category = "CinemaStudio",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Advanced",
                            EstimatedMinutes = 30,
                            IsPublished = true,
                            Slug = "cinema-studio",
                            SortOrder = 6,
                            Summary = "Director-level control over your AI videos",
                            Tags = "[\"cinema\",\"studio\",\"directing\"]",
                            Title = "Cinema Studio Masterclass"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            Category = "VisualEffects",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 20,
                            IsPublished = true,
                            Slug = "visual-effects",
                            SortOrder = 7,
                            Summary = "Apply 80+ VFX presets to your content",
                            Tags = "[\"vfx\",\"effects\",\"transitions\"]",
                            Title = "Visual Effects Library"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            Category = "Apps",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Beginner",
                            EstimatedMinutes = 15,
                            IsPublished = true,
                            Slug = "higgsfield-apps",
                            SortOrder = 8,
                            Summary = "One-click content creation with 60+ apps",
                            Tags = "[\"apps\",\"one-click\"]",
                            Title = "Using Higgsfield Apps"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            Category = "APIIntegration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 30,
                            IsPublished = true,
                            Slug = "api-quick-start",
                            SortOrder = 9,
                            Summary = "Integrate Higgsfield into your applications",
                            Tags = "[\"api\",\"integration\",\"rest\"]",
                            Title = "API Quick Start Guide"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            Category = "APIIntegration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 25,
                            IsPublished = true,
                            Slug = "python-sdk",
                            SortOrder = 10,
                            Summary = "Use the official Python client library",
                            Tags = "[\"python\",\"sdk\",\"api\"]",
                            Title = "Python SDK Deep Dive"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            Category = "APIIntegration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Advanced",
                            EstimatedMinutes = 20,
                            IsPublished = true,
                            Slug = "webhooks",
                            SortOrder = 11,
                            Summary = "Receive async notifications for generations",
                            Tags = "[\"webhooks\",\"api\",\"async\"]",
                            Title = "Webhook Integration"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            Category = "VideoGeneration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Advanced",
                            EstimatedMinutes = 25,
                            IsPublished = true,
                            Slug = "motion-control",
                            SortOrder = 12,
                            Summary = "Precise control of character actions and expressions",
                            Tags = "[\"motion\",\"kling\",\"character\"]",
                            Title = "Motion Control Tutorial"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            Category = "ImageGeneration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 20,
                            IsPublished = true,
                            Slug = "soul-2-fashion",
                            SortOrder = 13,
                            Summary = "Ultra-realistic fashion visuals with Soul 2.0",
                            Tags = "[\"soul\",\"fashion\",\"photography\"]",
                            Title = "Soul 2.0 Fashion Photography"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            Category = "ImageGeneration",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 15,
                            IsPublished = true,
                            Slug = "mixed-media",
                            SortOrder = 14,
                            Summary = "Layer mixed media styles for unique artwork",
                            Tags = "[\"mixed-media\",\"presets\",\"art\"]",
                            Title = "Mixed Media Presets"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            Category = "Advanced",
                            Content = "",
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DifficultyLevel = "Intermediate",
                            EstimatedMinutes = 20,
                            IsPublished = true,
                            Slug = "model-comparison",
                            SortOrder = 15,
                            Summary = "Choose the right model for your use case",
                            Tags = "[\"models\",\"comparison\",\"choosing\"]",
                            Title = "Model Comparison Guide"
                        });
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.TutorialResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TutorialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialResources");
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.TutorialStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeSnippet")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedResult")
                        .HasColumnType("text");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScreenshotUrl")
                        .HasColumnType("text");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Tip")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TutorialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TutorialId");

                    b.ToTable("TutorialSteps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExpectedResult = "You see the Higgsfield dashboard",
                            Instruction = "Visit higgsfield.ai and sign up for a free account. You can use Google or email signup.",
                            StepNumber = 1,
                            Title = "Create Your Account",
                            TutorialId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            ExpectedResult = "You can navigate between all main sections",
                            Instruction = "Familiarize yourself with the main navigation: Image, Video, Edit, Character, and Apps sections.",
                            StepNumber = 2,
                            Title = "Explore the Dashboard",
                            TutorialId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            ExpectedResult = "An AI-generated image appears within seconds",
                            Instruction = "Click on 'Image' > select 'Seedream 5.0 Lite' (free) > enter a prompt > toggle 'Unlimited' ON > click Generate",
                            StepNumber = 3,
                            Title = "Generate Your First Image",
                            TutorialId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            ExpectedResult = "Model selector shows available options",
                            Instruction = "Navigate to Image generation and select a model. Start with Seedream 5.0 Lite (free) or Nano Banana Pro for 4K quality.",
                            StepNumber = 1,
                            Title = "Choose Your Model",
                            TutorialId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            ExpectedResult = "High-quality image matching your description",
                            Instruction = "Be specific: include subject, style, lighting, camera angle, and quality modifiers. Example: 'A golden retriever puppy playing in autumn leaves, golden hour, professional photography, 85mm lens, bokeh'",
                            StepNumber = 2,
                            Title = "Write an Effective Prompt",
                            TutorialId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.TutorialResource", b =>
                {
                    b.HasOne("HiggsfieldTutorial.Domain.Entities.Tutorial", "Tutorial")
                        .WithMany("Resources")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutorial");
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.TutorialStep", b =>
                {
                    b.HasOne("HiggsfieldTutorial.Domain.Entities.Tutorial", "Tutorial")
                        .WithMany("Steps")
                        .HasForeignKey("TutorialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutorial");
                });

            modelBuilder.Entity("HiggsfieldTutorial.Domain.Entities.Tutorial", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
